CREATE DATABASE db_loja
	 ON PRIMARY (
	 NAME=db_loja,
	 FILENAME='C:\SQL\DB_Loja.MDF',
	 SIZE=6MB,
	 MAXSIZE=10MB
 )--USAR BASE DA LOJA

 USE DB_Loja--CRIACAO DE TABELAS

 --TABELA CONTENDO OS PRODUTOS
 CREATE TABLE tbl_Produtos
  (ID_PRODUTO SMALLINT PRIMARY KEY IDENTITY,
  NOME_PRODUTO VARCHAR(50) NOT NULL,
  PRECO MONEY NOT NULL) --TABELA COM OS NOMES DE CLIENTES

 CREATE TABLE tbl_Clientes
  (ID_CLIENTE SMALLINT PRIMARY KEY IDENTITY,
  NOME VARCHAR(50),
  SOBRENOME VARCHAR(60)) --TABELA COM A RELACAO DAS VENDAS

 CREATE TABLE tbl_Vendas
  (ID_PRODUTO SMALLINT NOT NULL
  CONSTRAINT fk_ID_PRODUTO FOREIGN KEY(ID_PRODUTO) REFERENCES TBL_PRODUTOS,
  ID_CLIENTE SMALLINT NOT NULL
  CONSTRAINT fk_ID_CLIENTES FOREIGN KEY(ID_CLIENTE) REFERENCES TBL_CLIENTES,
  DATA_VENDA DATE,
  QUANTIDADE SMALLINT NOT NULL)--INSERCAO DE DADOS

  --INSERCAO DOS DADOS DE CLIENTES
  INSERT INTO TBL_CLIENTES(NOME,SOBRENOME)VALUES('Daniel','Barret')
  INSERT INTO TBL_CLIENTES(NOME,SOBRENOME)VALUES('Gerald','Carter')
  INSERT INTO TBL_CLIENTES(NOME,SOBRENOME)VALUES('Mark','Sobell')
  INSERT INTO TBL_CLIENTES(NOME,SOBRENOME)VALUES('William','Stanek')
  INSERT INTO TBL_CLIENTES(NOME,SOBRENOME)VALUES('Richard','Blum')  --INSERCAO DOS DADOS DE PRODUTOS

  INSERT INTO TBL_PRODUTOS(NOME_PRODUTO,PRECO)VALUES('Mouse',30.00)
  INSERT INTO TBL_PRODUTOS(NOME_PRODUTO,PRECO)VALUES('Teclado',40.00)
  INSERT INTO TBL_PRODUTOS(NOME_PRODUTO,PRECO)VALUES('Monitor LCD',399.99)
  INSERT INTO TBL_PRODUTOS(NOME_PRODUTO,PRECO)VALUES('Disco SSD',99.99)
  INSERT INTO TBL_PRODUTOS(NOME_PRODUTO,PRECO)VALUES('Cabo HDMI',80.00)
  INSERT INTO TBL_PRODUTOS(NOME_PRODUTO,PRECO)VALUES('Mouse Pad',30.00)  --INSERCAO DOS DADOS DE VENDAS

  INSERT INTO TBL_VENDAS(ID_PRODUTO,ID_CLIENTE,DATA_VENDA,QUANTIDADE)VALUES(1,2,'01/01/2015',2)
  INSERT INTO TBL_VENDAS(ID_PRODUTO,ID_CLIENTE,DATA_VENDA,QUANTIDADE)VALUES(1,1,'05/06/2015',2)
  INSERT INTO TBL_VENDAS(ID_PRODUTO,ID_CLIENTE,DATA_VENDA,QUANTIDADE)VALUES(3,2,'09/10/2015',3)
  INSERT INTO TBL_VENDAS(ID_PRODUTO,ID_CLIENTE,DATA_VENDA,QUANTIDADE)VALUES(4,2,'01/08/2015',4)
  INSERT INTO TBL_VENDAS(ID_PRODUTO,ID_CLIENTE,DATA_VENDA,QUANTIDADE)VALUES(6,2,'03/26/2015',2)
  INSERT INTO TBL_VENDAS(ID_PRODUTO,ID_CLIENTE,DATA_VENDA,QUANTIDADE)VALUES(2,2,'03/24/2015',1)
  INSERT INTO TBL_VENDAS(ID_PRODUTO,ID_CLIENTE,DATA_VENDA,QUANTIDADE)VALUES(5,2,'03/25/2015',1)
  INSERT INTO TBL_VENDAS(ID_PRODUTO,ID_CLIENTE,DATA_VENDA,QUANTIDADE)VALUES(2,3,'03/26/2015',1)
  INSERT INTO TBL_VENDAS(ID_PRODUTO,ID_CLIENTE,DATA_VENDA,QUANTIDADE)VALUES(2,4,'03/28/2015',1)
  INSERT INTO TBL_VENDAS(ID_PRODUTO,ID_CLIENTE,DATA_VENDA,QUANTIDADE)VALUES(4,5,'03/29/2015',1)